/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.68
 * Generated at: 2016-09-05 08:17:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.javascript;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class SubscriptionFunctions_js_002dblock_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/tlds/iteratec-tags.tld", Long.valueOf(1471878616000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      //  tilesx:useAttribute
      org.apache.tiles.jsp.taglib.UseAttributeTag _jspx_th_tilesx_005fuseAttribute_005f0 = (new org.apache.tiles.jsp.taglib.UseAttributeTag());
      _jsp_getInstanceManager().newInstance(_jspx_th_tilesx_005fuseAttribute_005f0);
      _jspx_th_tilesx_005fuseAttribute_005f0.setJspContext(_jspx_page_context);
      // /javascript/SubscriptionFunctions.js-block.jsp(8,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tilesx_005fuseAttribute_005f0.setName("service_class");
      // /javascript/SubscriptionFunctions.js-block.jsp(8,0) name = ignore type = boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tilesx_005fuseAttribute_005f0.setIgnore(true);
      _jspx_th_tilesx_005fuseAttribute_005f0.doTag();
      java.lang.Object service_class = null;
      service_class = (java.lang.Object) _jspx_page_context.findAttribute("service_class");
      _jsp_getInstanceManager().destroyInstance(_jspx_th_tilesx_005fuseAttribute_005f0);
      //  tilesx:useAttribute
      org.apache.tiles.jsp.taglib.UseAttributeTag _jspx_th_tilesx_005fuseAttribute_005f1 = (new org.apache.tiles.jsp.taglib.UseAttributeTag());
      _jsp_getInstanceManager().newInstance(_jspx_th_tilesx_005fuseAttribute_005f1);
      _jspx_th_tilesx_005fuseAttribute_005f1.setJspContext(_jspx_page_context);
      // /javascript/SubscriptionFunctions.js-block.jsp(9,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tilesx_005fuseAttribute_005f1.setName("subscribed_element");
      _jspx_th_tilesx_005fuseAttribute_005f1.doTag();
      java.lang.Object subscribed_element = null;
      subscribed_element = (java.lang.Object) _jspx_page_context.findAttribute("subscribed_element");
      _jsp_getInstanceManager().destroyInstance(_jspx_th_tilesx_005fuseAttribute_005f1);
      //  tilesx:useAttribute
      org.apache.tiles.jsp.taglib.UseAttributeTag _jspx_th_tilesx_005fuseAttribute_005f2 = (new org.apache.tiles.jsp.taglib.UseAttributeTag());
      _jsp_getInstanceManager().newInstance(_jspx_th_tilesx_005fuseAttribute_005f2);
      _jspx_th_tilesx_005fuseAttribute_005f2.setJspContext(_jspx_page_context);
      // /javascript/SubscriptionFunctions.js-block.jsp(10,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tilesx_005fuseAttribute_005f2.setName("id");
      // /javascript/SubscriptionFunctions.js-block.jsp(10,0) name = ignore type = boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tilesx_005fuseAttribute_005f2.setIgnore(true);
      _jspx_th_tilesx_005fuseAttribute_005f2.doTag();
      java.lang.Object id = null;
      id = (java.lang.Object) _jspx_page_context.findAttribute("id");
      _jsp_getInstanceManager().destroyInstance(_jspx_th_tilesx_005fuseAttribute_005f2);
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /javascript/SubscriptionFunctions.js-block.jsp(12,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("functionalPermission");
    // /javascript/SubscriptionFunctions.js-block.jsp(12,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/javascript/SubscriptionFunctions.js-block.jsp(12,0) '${userContext.perms.userHasFuncPermSubscription}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${userContext.perms.userHasFuncPermSubscription}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f1.setParent(null);
    // /javascript/SubscriptionFunctions.js-block.jsp(13,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setVar("functionalPermissionShowSubscribers");
    // /javascript/SubscriptionFunctions.js-block.jsp(13,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/javascript/SubscriptionFunctions.js-block.jsp(13,0) '${userContext.perms.userHasFuncPermShowSubscribers}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${userContext.perms.userHasFuncPermShowSubscribers}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
    if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /javascript/SubscriptionFunctions.js-block.jsp(15,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty service_class}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<script type=\"text/javascript\">\r\n");
        out.write("//<![CDATA[\r\n");
        out.write("\tvar subscribedUsers = new Array();\r\n");
        out.write("\t");
        if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("  \tvar subscribed = ");
        if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write(";\r\n");
        out.write("  \tvar funcPerm = ");
        if (_jspx_meth_c_005fout_005f2(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write(";\r\n");
        out.write("\r\n");
        out.write("  \t// update all button labels as soon as the page has loaded and our variables from above have been initialized \r\n");
        out.write("  \t$(document).ready(function() {\r\n");
        out.write("  \t\tupdateSubscribeLabels(subscribed, subscribedUsers.length);\r\n");
        out.write("  \t});\r\n");
        out.write("\r\n");
        out.write("  \tfunction doSubscribe() {\r\n");
        out.write("  \t  \tif (subscribed) {\r\n");
        out.write("\t\t\tunsubscribe();\r\n");
        out.write("\t\t} else {\r\n");
        out.write("\t\t\tsubscribe();\r\n");
        out.write("\t\t}\r\n");
        out.write("  \t}\r\n");
        out.write("  \t\r\n");
        out.write("  \tfunction unsubscribe() {\r\n");
        out.write("  \t\t");
        if (_jspx_meth_c_005fout_005f3(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write(".unsubscribe(");
        if (_jspx_meth_c_005fout_005f4(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write(", function(n) { \r\n");
        out.write("\t\t\t\r\n");
        out.write("  \t\t\tshowPopupDialog(\"");
        if (_jspx_meth_itera_005fmessage_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("\", \"");
        if (_jspx_meth_itera_005fmessage_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write(".\");\r\n");
        out.write("\t\t\tif (funcPerm) {\r\n");
        out.write("\t\t\t\tvar indexOf = $.inArray('");
        if (_jspx_meth_c_005fout_005f5(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("', subscribedUsers);\r\n");
        out.write("\t\t\t\tif (indexOf > -1) {\r\n");
        out.write("\t\t\t\t\tsubscribedUsers.splice($.inArray(subscribedUsers), 1);\r\n");
        out.write("\t\t\t\t}\r\n");
        out.write("\t\t\t} \r\n");
        out.write("\t\t\tsubscribed = false; \r\n");
        out.write("\t\t\tupdateSubscribeLabels(subscribed, n);\r\n");
        out.write("\t\t});\r\n");
        out.write("  \t}\r\n");
        out.write("  \t\r\n");
        out.write("  \tfunction subscribe() {\r\n");
        out.write("  \t\tvar emailProvided = ('");
        if (_jspx_meth_c_005fout_005f6(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("' != '');\r\n");
        out.write("  \t  \tif (!emailProvided) {\r\n");
        out.write("  \t  \t   showPopupDialog(\"");
        if (_jspx_meth_itera_005fmessage_005f2(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("\", \"");
        if (_jspx_meth_itera_005fmessage_005f3(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("\");\r\n");
        out.write("   \t  \t} else {\r\n");
        out.write("  \t\t\t");
        if (_jspx_meth_c_005fout_005f7(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write(".subscribe(");
        if (_jspx_meth_c_005fout_005f8(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write(", function(n) {\r\n");
        out.write("  \t\t\t\r\n");
        out.write("\t\t\t\tshowPopupDialog(\"");
        if (_jspx_meth_itera_005fmessage_005f4(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("\", \"");
        if (_jspx_meth_itera_005fmessage_005f5(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write(".\");\r\n");
        out.write("\t\t\t\tif (funcPerm) { \r\n");
        out.write("\t\t\t\t\tsubscribedUsers.push('");
        if (_jspx_meth_c_005fout_005f9(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("');\r\n");
        out.write("\t\t\t\t}\r\n");
        out.write("\t\t\t\tsubscribed = true;\r\n");
        out.write("\t\t\t\tupdateSubscribeLabels(subscribed, n);\r\n");
        out.write("  \t\t\t});\r\n");
        out.write("   \t  \t}\r\n");
        out.write("  \t}\r\n");
        out.write("\r\n");
        out.write("  \tfunction showSubscribedUsers() {\r\n");
        out.write("  \t\tif (funcPerm) {\r\n");
        out.write("  \t\t\tsubscribedUsers.sort();\r\n");
        out.write("  \t\t\tvar list = '';\r\n");
        out.write("  \t\t\tif (subscribedUsers.length > 0) {\r\n");
        out.write("  \t\t\t\t");
        out.write("\r\n");
        out.write("  \t\t\t\tlist = '<ul><li>' + subscribedUsers.join('</li><li>') + '</li></ul>';\r\n");
        out.write("  \t\t\t} else {\r\n");
        out.write("  \t\t\t\tlist = \"");
        if (_jspx_meth_itera_005fmessage_005f6(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write(".\";\r\n");
        out.write("  \t\t\t}\r\n");
        out.write("  \t\t\tshowPopupDialog(\"");
        if (_jspx_meth_itera_005fmessage_005f7(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write(":\", list);\r\n");
        out.write("  \t\t} else {\r\n");
        out.write("  \t\t\tshowPopupDialog(\"");
        if (_jspx_meth_itera_005fmessage_005f8(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write(":\", \"");
        if (_jspx_meth_itera_005fmessage_005f9(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("\");\r\n");
        out.write("  \t\t}\r\n");
        out.write("  \t}\r\n");
        out.write("  \t\r\n");
        out.write("  \tfunction updateSubscribeLabels(isSubscribed, subscribersCount) {\r\n");
        out.write("\t\t$('span.subscribercount').each(function() {\r\n");
        out.write("\t\t\t$(this).text('(' + subscribersCount + ')');\r\n");
        out.write("\t\t});\r\n");
        out.write("\t\t$('span.subscribe_button').each(function() {\r\n");
        out.write("\t\t\tif (isSubscribed === true) {\r\n");
        out.write("\t\t\t\t$(this).text('");
        if (_jspx_meth_itera_005fmessage_005f10(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("');\r\n");
        out.write("\t\t\t} else if (isSubscribed === false) {\r\n");
        out.write("\t\t\t\t$(this).text('");
        if (_jspx_meth_itera_005fmessage_005f11(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("');\r\n");
        out.write("\t\t\t}\r\n");
        out.write("\t\t});\r\n");
        out.write("  \t}\r\n");
        out.write("  \t\r\n");
        out.write("//]]>\r\n");
        out.write("</script>\r\n");
        out.write("\r\n");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /javascript/SubscriptionFunctions.js-block.jsp(20,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${functionalPermissionShowSubscribers == true and not empty subscribed_element.subscribedUsers}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f1, _jspx_page_context))
          return true;
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
    // /javascript/SubscriptionFunctions.js-block.jsp(21,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("user");
    // /javascript/SubscriptionFunctions.js-block.jsp(21,2) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/javascript/SubscriptionFunctions.js-block.jsp(21,2) '${subscribed_element.subscribedUsers}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${subscribed_element.subscribedUsers}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\tsubscribedUsers.push('");
          if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("');\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /javascript/SubscriptionFunctions.js-block.jsp(22,25) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.loginName}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /javascript/SubscriptionFunctions.js-block.jsp(25,20) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${subscribed_element.subscribed}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
    if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /javascript/SubscriptionFunctions.js-block.jsp(26,18) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${functionalPermissionShowSubscribers}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
    if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /javascript/SubscriptionFunctions.js-block.jsp(42,4) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${service_class}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
    if (_jspx_th_c_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f4 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /javascript/SubscriptionFunctions.js-block.jsp(42,50) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f4 = _jspx_th_c_005fout_005f4.doStartTag();
    if (_jspx_th_c_005fout_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f4);
    return false;
  }

  private boolean _jspx_meth_itera_005fmessage_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  itera:message
    de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag _jspx_th_itera_005fmessage_005f0 = (de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag) _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.get(de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag.class);
    _jspx_th_itera_005fmessage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_itera_005fmessage_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /javascript/SubscriptionFunctions.js-block.jsp(44,22) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_itera_005fmessage_005f0.setKey("global.unsubscription.successful");
    int _jspx_eval_itera_005fmessage_005f0 = _jspx_th_itera_005fmessage_005f0.doStartTag();
    if (_jspx_th_itera_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_itera_005fmessage_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_itera_005fmessage_005f0);
    return false;
  }

  private boolean _jspx_meth_itera_005fmessage_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  itera:message
    de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag _jspx_th_itera_005fmessage_005f1 = (de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag) _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.get(de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag.class);
    _jspx_th_itera_005fmessage_005f1.setPageContext(_jspx_page_context);
    _jspx_th_itera_005fmessage_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /javascript/SubscriptionFunctions.js-block.jsp(44,82) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_itera_005fmessage_005f1.setKey("global.unsubscription.successful");
    int _jspx_eval_itera_005fmessage_005f1 = _jspx_th_itera_005fmessage_005f1.doStartTag();
    if (_jspx_th_itera_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_itera_005fmessage_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_itera_005fmessage_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f5 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /javascript/SubscriptionFunctions.js-block.jsp(46,29) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f5.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userContext.user.loginName}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f5 = _jspx_th_c_005fout_005f5.doStartTag();
    if (_jspx_th_c_005fout_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f5);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f6 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f6.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /javascript/SubscriptionFunctions.js-block.jsp(57,26) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f6.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userContext.user.email}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f6 = _jspx_th_c_005fout_005f6.doStartTag();
    if (_jspx_th_c_005fout_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f6);
    return false;
  }

  private boolean _jspx_meth_itera_005fmessage_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  itera:message
    de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag _jspx_th_itera_005fmessage_005f2 = (de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag) _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.get(de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag.class);
    _jspx_th_itera_005fmessage_005f2.setPageContext(_jspx_page_context);
    _jspx_th_itera_005fmessage_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /javascript/SubscriptionFunctions.js-block.jsp(59,26) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_itera_005fmessage_005f2.setKey("errorview.headline");
    int _jspx_eval_itera_005fmessage_005f2 = _jspx_th_itera_005fmessage_005f2.doStartTag();
    if (_jspx_th_itera_005fmessage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_itera_005fmessage_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_itera_005fmessage_005f2);
    return false;
  }

  private boolean _jspx_meth_itera_005fmessage_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  itera:message
    de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag _jspx_th_itera_005fmessage_005f3 = (de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag) _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.get(de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag.class);
    _jspx_th_itera_005fmessage_005f3.setPageContext(_jspx_page_context);
    _jspx_th_itera_005fmessage_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /javascript/SubscriptionFunctions.js-block.jsp(59,72) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_itera_005fmessage_005f3.setKey("global.subscribe.email.missing");
    int _jspx_eval_itera_005fmessage_005f3 = _jspx_th_itera_005fmessage_005f3.doStartTag();
    if (_jspx_th_itera_005fmessage_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_itera_005fmessage_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_itera_005fmessage_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f7 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f7.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /javascript/SubscriptionFunctions.js-block.jsp(61,5) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f7.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${service_class}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f7 = _jspx_th_c_005fout_005f7.doStartTag();
    if (_jspx_th_c_005fout_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f7);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f7);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f8 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f8.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /javascript/SubscriptionFunctions.js-block.jsp(61,49) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f8.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f8 = _jspx_th_c_005fout_005f8.doStartTag();
    if (_jspx_th_c_005fout_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f8);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f8);
    return false;
  }

  private boolean _jspx_meth_itera_005fmessage_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  itera:message
    de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag _jspx_th_itera_005fmessage_005f4 = (de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag) _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.get(de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag.class);
    _jspx_th_itera_005fmessage_005f4.setPageContext(_jspx_page_context);
    _jspx_th_itera_005fmessage_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /javascript/SubscriptionFunctions.js-block.jsp(63,21) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_itera_005fmessage_005f4.setKey("global.subscription.successful");
    int _jspx_eval_itera_005fmessage_005f4 = _jspx_th_itera_005fmessage_005f4.doStartTag();
    if (_jspx_th_itera_005fmessage_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_itera_005fmessage_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_itera_005fmessage_005f4);
    return false;
  }

  private boolean _jspx_meth_itera_005fmessage_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  itera:message
    de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag _jspx_th_itera_005fmessage_005f5 = (de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag) _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.get(de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag.class);
    _jspx_th_itera_005fmessage_005f5.setPageContext(_jspx_page_context);
    _jspx_th_itera_005fmessage_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /javascript/SubscriptionFunctions.js-block.jsp(63,79) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_itera_005fmessage_005f5.setKey("global.subscription.successful");
    int _jspx_eval_itera_005fmessage_005f5 = _jspx_th_itera_005fmessage_005f5.doStartTag();
    if (_jspx_th_itera_005fmessage_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_itera_005fmessage_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_itera_005fmessage_005f5);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f9(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f9 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f9.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f9.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /javascript/SubscriptionFunctions.js-block.jsp(65,27) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f9.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userContext.user.loginName}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f9 = _jspx_th_c_005fout_005f9.doStartTag();
    if (_jspx_th_c_005fout_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f9);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f9);
    return false;
  }

  private boolean _jspx_meth_itera_005fmessage_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  itera:message
    de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag _jspx_th_itera_005fmessage_005f6 = (de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag) _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.get(de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag.class);
    _jspx_th_itera_005fmessage_005f6.setPageContext(_jspx_page_context);
    _jspx_th_itera_005fmessage_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /javascript/SubscriptionFunctions.js-block.jsp(81,14) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_itera_005fmessage_005f6.setKey("global.subscribed.users.emtpy");
    int _jspx_eval_itera_005fmessage_005f6 = _jspx_th_itera_005fmessage_005f6.doStartTag();
    if (_jspx_th_itera_005fmessage_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_itera_005fmessage_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_itera_005fmessage_005f6);
    return false;
  }

  private boolean _jspx_meth_itera_005fmessage_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  itera:message
    de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag _jspx_th_itera_005fmessage_005f7 = (de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag) _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.get(de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag.class);
    _jspx_th_itera_005fmessage_005f7.setPageContext(_jspx_page_context);
    _jspx_th_itera_005fmessage_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /javascript/SubscriptionFunctions.js-block.jsp(83,22) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_itera_005fmessage_005f7.setKey("global.subscribed.users");
    int _jspx_eval_itera_005fmessage_005f7 = _jspx_th_itera_005fmessage_005f7.doStartTag();
    if (_jspx_th_itera_005fmessage_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_itera_005fmessage_005f7);
      return true;
    }
    _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_itera_005fmessage_005f7);
    return false;
  }

  private boolean _jspx_meth_itera_005fmessage_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  itera:message
    de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag _jspx_th_itera_005fmessage_005f8 = (de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag) _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.get(de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag.class);
    _jspx_th_itera_005fmessage_005f8.setPageContext(_jspx_page_context);
    _jspx_th_itera_005fmessage_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /javascript/SubscriptionFunctions.js-block.jsp(85,22) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_itera_005fmessage_005f8.setKey("global.subscribed.users");
    int _jspx_eval_itera_005fmessage_005f8 = _jspx_th_itera_005fmessage_005f8.doStartTag();
    if (_jspx_th_itera_005fmessage_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_itera_005fmessage_005f8);
      return true;
    }
    _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_itera_005fmessage_005f8);
    return false;
  }

  private boolean _jspx_meth_itera_005fmessage_005f9(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  itera:message
    de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag _jspx_th_itera_005fmessage_005f9 = (de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag) _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.get(de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag.class);
    _jspx_th_itera_005fmessage_005f9.setPageContext(_jspx_page_context);
    _jspx_th_itera_005fmessage_005f9.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /javascript/SubscriptionFunctions.js-block.jsp(85,74) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_itera_005fmessage_005f9.setKey("global.subscribe.no.permission");
    int _jspx_eval_itera_005fmessage_005f9 = _jspx_th_itera_005fmessage_005f9.doStartTag();
    if (_jspx_th_itera_005fmessage_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_itera_005fmessage_005f9);
      return true;
    }
    _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_itera_005fmessage_005f9);
    return false;
  }

  private boolean _jspx_meth_itera_005fmessage_005f10(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  itera:message
    de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag _jspx_th_itera_005fmessage_005f10 = (de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag) _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.get(de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag.class);
    _jspx_th_itera_005fmessage_005f10.setPageContext(_jspx_page_context);
    _jspx_th_itera_005fmessage_005f10.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /javascript/SubscriptionFunctions.js-block.jsp(95,18) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_itera_005fmessage_005f10.setKey("global.unsubscribe");
    int _jspx_eval_itera_005fmessage_005f10 = _jspx_th_itera_005fmessage_005f10.doStartTag();
    if (_jspx_th_itera_005fmessage_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_itera_005fmessage_005f10);
      return true;
    }
    _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_itera_005fmessage_005f10);
    return false;
  }

  private boolean _jspx_meth_itera_005fmessage_005f11(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  itera:message
    de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag _jspx_th_itera_005fmessage_005f11 = (de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag) _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.get(de.iteratec.iteraplan.presentation.tags.EscapedKeyMessageTag.class);
    _jspx_th_itera_005fmessage_005f11.setPageContext(_jspx_page_context);
    _jspx_th_itera_005fmessage_005f11.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /javascript/SubscriptionFunctions.js-block.jsp(97,18) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_itera_005fmessage_005f11.setKey("global.subscribe");
    int _jspx_eval_itera_005fmessage_005f11 = _jspx_th_itera_005fmessage_005f11.doStartTag();
    if (_jspx_th_itera_005fmessage_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_itera_005fmessage_005f11);
      return true;
    }
    _005fjspx_005ftagPool_005fitera_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_itera_005fmessage_005f11);
    return false;
  }
}
