///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace IteraPlanTests.Web
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddNewProject_1 recording.
    /// </summary>
    [TestModule("375bd994-1079-4fdd-a441-51823d5abb27", ModuleType.Recording, 1)]
    public partial class AddNewProject_1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the IteraPlanTests.IteraPlanTestsRepository repository.
        /// </summary>
        public static IteraPlanTests.IteraPlanTestsRepository repo = IteraPlanTests.IteraPlanTestsRepository.Instance;

        static AddNewProject_1 instance = new AddNewProject_1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddNewProject_1()
        {
            varProjectName = "MyNewProject";
            varDescription = "Description this project";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddNewProject_1 Instance
        {
            get { return instance; }
        }

#region Variables

        string _varProjectName;

        /// <summary>
        /// Gets or sets the value of variable varProjectName.
        /// </summary>
        [TestVariable("4ec5ea6a-898c-4232-9cfe-882dacaa136b")]
        public string varProjectName
        {
            get { return _varProjectName; }
            set { _varProjectName = value; }
        }

        string _varDescription;

        /// <summary>
        /// Gets or sets the value of variable varDescription.
        /// </summary>
        [TestVariable("ec477989-1868-43d9-b470-5ce643cc7c30")]
        public string varDescription
        {
            get { return _varDescription; }
            set { _varDescription = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeIteraplan.NameField' at 50;15.", repo.WelcomeIteraplan.NameFieldInfo, new RecordItemIndex(0));
            repo.WelcomeIteraplan.NameField.Click("50;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varProjectName' with focus on 'WelcomeIteraplan.NameField'.", repo.WelcomeIteraplan.NameFieldInfo, new RecordItemIndex(1));
            repo.WelcomeIteraplan.NameField.PressKeys(varProjectName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeIteraplan.DescriptionTextarea' at 78;50.", repo.WelcomeIteraplan.DescriptionTextareaInfo, new RecordItemIndex(2));
            repo.WelcomeIteraplan.DescriptionTextarea.Click("78;50");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varDescription' with focus on 'WelcomeIteraplan.DescriptionTextarea'.", repo.WelcomeIteraplan.DescriptionTextareaInfo, new RecordItemIndex(3));
            repo.WelcomeIteraplan.DescriptionTextarea.PressKeys(varDescription);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeIteraplan.PeriodStartDate' at 87;10.", repo.WelcomeIteraplan.PeriodStartDateInfo, new RecordItemIndex(4));
            repo.WelcomeIteraplan.PeriodStartDate.Click("87;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeIteraplan.TableTagTableCondensed.SomeThTag' at 10;13.", repo.WelcomeIteraplan.TableTagTableCondensed.SomeThTagInfo, new RecordItemIndex(5));
            repo.WelcomeIteraplan.TableTagTableCondensed.SomeThTag.Click("10;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeIteraplan.TableTagTableCondensed.TdTag3' at 16;7.", repo.WelcomeIteraplan.TableTagTableCondensed.TdTag3Info, new RecordItemIndex(6));
            repo.WelcomeIteraplan.TableTagTableCondensed.TdTag3.Click("16;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeIteraplan.PeriodEndDate' at 61;19.", repo.WelcomeIteraplan.PeriodEndDateInfo, new RecordItemIndex(7));
            repo.WelcomeIteraplan.PeriodEndDate.Click("61;19");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeIteraplan.TableTagTableCondensed.SomeThTag' at 11;15.", repo.WelcomeIteraplan.TableTagTableCondensed.SomeThTagInfo, new RecordItemIndex(8));
            repo.WelcomeIteraplan.TableTagTableCondensed.SomeThTag.Click("11;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeIteraplan.TableTagTableCondensed.SomeThTag' at 8;15.", repo.WelcomeIteraplan.TableTagTableCondensed.SomeThTagInfo, new RecordItemIndex(9));
            repo.WelcomeIteraplan.TableTagTableCondensed.SomeThTag.Click("8;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeIteraplan.TableTagTableCondensed.TdTag30' at 10;11.", repo.WelcomeIteraplan.TableTagTableCondensed.TdTag30Info, new RecordItemIndex(10));
            repo.WelcomeIteraplan.TableTagTableCondensed.TdTag30.Click("10;11");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
