///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace IteraPlanTests.Web
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The InstantRelatesProject recording.
    /// </summary>
    [TestModule("549c5ba8-accb-46c5-9eba-bb3f1e5b3ffe", ModuleType.Recording, 1)]
    public partial class InstantRelatesProject : ITestModule
    {
        /// <summary>
        /// Holds an instance of the IteraPlanTests.IteraPlanTestsRepository repository.
        /// </summary>
        public static IteraPlanTests.IteraPlanTestsRepository repo = IteraPlanTests.IteraPlanTestsRepository.Instance;

        static InstantRelatesProject instance = new InstantRelatesProject();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InstantRelatesProject()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InstantRelatesProject Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeIteraplan.UiButtonIconPrimaryUiIconUiIconT1' at 1;7.", repo.WelcomeIteraplan.UiButtonIconPrimaryUiIconUiIconT1Info, new RecordItemIndex(0));
            repo.WelcomeIteraplan.UiButtonIconPrimaryUiIconUiIconT1.Click("1;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeIteraplan.UiAutocompleteUiMenuUiWidgetUiWid2' at 329;128.", repo.WelcomeIteraplan.UiAutocompleteUiMenuUiWidgetUiWid2Info, new RecordItemIndex(1));
            repo.WelcomeIteraplan.UiAutocompleteUiMenuUiWidgetUiWid2.Click("329;128");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeIteraplan.UiAutocompleteUiMenuUiWidgetUiWid2' at 147;17.", repo.WelcomeIteraplan.UiAutocompleteUiMenuUiWidgetUiWid2Info, new RecordItemIndex(2));
            repo.WelcomeIteraplan.UiAutocompleteUiMenuUiWidgetUiWid2.Click("147;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeIteraplan.IconPlus1' at 8;7.", repo.WelcomeIteraplan.IconPlus1Info, new RecordItemIndex(3));
            repo.WelcomeIteraplan.IconPlus1.Click("8;7");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
