///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace IteraPlanTests.Web
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SearchProjects recording.
    /// </summary>
    [TestModule("20e5b0fc-62f9-46a9-a8c3-d082b27871df", ModuleType.Recording, 1)]
    public partial class SearchProjects : ITestModule
    {
        /// <summary>
        /// Holds an instance of the IteraPlanTests.IteraPlanTestsRepository repository.
        /// </summary>
        public static IteraPlanTests.IteraPlanTestsRepository repo = IteraPlanTests.IteraPlanTestsRepository.Instance;

        static SearchProjects instance = new SearchProjects();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SearchProjects()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SearchProjects Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeIteraplan.IteraplanHeaderImage1' at 109;24.", repo.WelcomeIteraplan.IteraplanHeaderImage1Info, new RecordItemIndex(0));
            repo.WelcomeIteraplan.IteraplanHeaderImage1.Click("109;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeIteraplan.Project' at 61;52.", repo.WelcomeIteraplan.ProjectInfo, new RecordItemIndex(1));
            repo.WelcomeIteraplan.Project.Click("61;52");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer.IteraPlanTestsRanorexStudio' at 25;26.", repo.Explorer.IteraPlanTestsRanorexStudioInfo, new RecordItemIndex(2));
            repo.Explorer.IteraPlanTestsRanorexStudio.Click("25;26");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
