///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace IteraPlanTests.Web
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SwitchToInteractiveClient3 recording.
    /// </summary>
    [TestModule("70e43bed-12fb-4fa9-8770-dd9873f4bb2c", ModuleType.Recording, 1)]
    public partial class SwitchToInteractiveClient3 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyNewRepository repository.
        /// </summary>
        public static MyNewRepository repo = MyNewRepository.Instance;

        static SwitchToInteractiveClient3 instance = new SwitchToInteractiveClient3();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SwitchToInteractiveClient3()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SwitchToInteractiveClient3 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeIteraplan.SwitchToInteractiveClient' at 48;20.", repo.WelcomeIteraplan.SwitchToInteractiveClientInfo, new RecordItemIndex(0));
            repo.WelcomeIteraplan.SwitchToInteractiveClient.Click("48;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IteraplanHome.IpDataTiles' at 1464;7.", repo.IteraplanHome.IpDataTilesInfo, new RecordItemIndex(1));
            repo.IteraplanHome.IpDataTiles.Click("1464;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IteraplanHome.HttpLocalhost8080IteraplanClientH' at 111;33.", repo.IteraplanHome.HttpLocalhost8080IteraplanClientHInfo, new RecordItemIndex(2));
            repo.IteraplanHome.HttpLocalhost8080IteraplanClientH.Click("111;33");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Projects.GreenIT'.", repo.Projects.GreenITInfo, new RecordItemIndex(3));
            Validate.Exists(repo.Projects.GreenITInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
